name: CI/CD with SonarQube and IIS Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy to IIS
    runs-on: self-hosted  # Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SonarQube Scan (Windows Local)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        sonar-scanner.bat ^
          -Dsonar.host.url=%SONAR_HOST_URL% ^
          -Dsonar.login=%SONAR_TOKEN%
      shell: cmd

    - name: Stop IIS Website
      shell: powershell
      run: |
        Stop-Website -Name "mysite"

    - name: Deploy to IIS
      shell: powershell
      run: |
        Copy-Item -Path "$(pwd)\published\*" -Destination "C:\myapp\app-new\sonar-test-new\" -Recurse

    - name: Start IIS Website
      shell: powershell
      run: |
        Start-Website -Name "mysite"
