name: CI/CD with SonarQube and IIS Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy to IIS
    runs-on: self-hosted  # Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SonarQube Scan (Windows Local)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        sonar-scanner.bat ^
          -Dsonar.host.url=%SONAR_HOST_URL% ^
          -Dsonar.login=%SONAR_TOKEN%
      shell: cmd

    - name: Deploy to IIS
      run: |
        
        Remove-Item -Recurse -Force "C:\inetpub\wwwroot\mysite\*" -ErrorAction SilentlyContinue
        Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Exclude ".git", ".github" | Copy-Item -Destination "C:\inetpub\wwwroot\mysite" -Recurse -Force
        Import-Module WebAdministration
        Stop-Website -Name "mysite"
        Start-Website -Name "mysite"
      shell: powershell
